services:
    david63.profileredirect.listener:
        class: david63\profileredirect\event\listener
        arguments:
            - '@config'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'
            - '@david63.profileredirect.core.functions'
        tags:
            - { name: event.listener }

    david63.profileredirect.admin.controller:
        class: david63\profileredirect\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@language'
            - '@david63.profileredirect.core.functions'

    david63.profileredirect.core.functions:
        class: david63\profileredirect\core\functions
        arguments:
            - '@ext.manager'

    _defaults:
        public: true
